repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: debug-statements
      - id: name-tests-test
      - id: trailing-whitespace

  - repo: https://github.com/ambv/black
    rev: 19.10b0
    hooks:
      - id: black
        language_version: python3.7

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v1.8.0
    hooks:
      - id: reorder-python-imports
        language_version: python3

  #https://docs.pylint.org/en/1.6.0/tutorial.html
  - repo: https://github.com/coldnight/pre-commit-pylint.git
    rev: v0.0.3
    hooks:
      - id: pylint-score-limit
        args:
          - --disable=all
          - --enable=F,E,similarities,unreachable,duplicate-key,unnecessary-semicolon,global-variable-not-assigned,unused-variable,binary-op-exception,bad-format-string,anomalous-backslash-in-string,bad-open-mode
          - --disable=E0402,E0401,E1101,E0213,E0602,E0211,E0611
          - --limit=6

  - repo: https://github.com/coldnight/pre-commit-pylint.git
    rev: v0.0.3
    hooks:
      - id: pylint-score-limit
        name: pylint-similarities
        args:
          - --disable=all
          - --enable=similarities
          - --disable=E0402,E0401,E1101,E0213,E0602
          - --limit=10

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pipenv run pytest
        language: system
        pass_filenames: false
        always_run: true

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.740
    hooks:
      - id: mypy
        args: [--no-strict-optional, --ignore-missing-imports]
